### ISSUE TITLE
[Bug] Script fails on first run - but consistently works on second

### ISSUE THREAD

**Issue by markoprodanovic** [markoprodanovic/quiz-reports#8]
I suspect it has something to do with creating then downloading the report.
Revisit the logic where we wait for the report to get created then download it.

**Comment by alisonmyers** [comment]
- add a check to see if report needs to be regenerated
- if yes then regenerate

- when no report generated 
- add a timeout
- if our script doesn't download in the time - have user manually generate the report and try again once done
